# Generated by Django 4.1.3 on 2023-06-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
