# Generated by Django 4.1.3 on 2023-06-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0002_alter_host_switch_id_alter_link_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='link',
        ),
    ]
