# Generated by Django 4.1.3 on 2023-06-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0004_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_switch',
            old_name='switch_num',
            new_name='switch_dpid',
        ),
    ]
