# Generated by Django 4.1.3 on 2023-06-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0005_rename_switch_num_host_switch_switch_dpid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='host_switch',
        ),
        migrations.DeleteModel(
            name='link',
        ),
    ]
