# Generated by Django 4.1.3 on 2023-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuxi', '0006_delete_host_switch_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_switch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_ip', models.CharField(max_length=50)),
                ('host_mac', models.CharField(max_length=50)),
                ('switch_dpid', models.IntegerField()),
                ('switch_port', models.IntegerField()),
            ],
            options={
                'db_table': 'host_switch',
            },
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_dpid', models.IntegerField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('dst_dpid', models.IntegerField()),
                ('link_status', models.CharField(default='up', max_length=12)),
                ('link_bandwidth', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'link',
                'unique_together': {('src_dpid', 'src_port', 'dst_port', 'dst_dpid')},
            },
        ),
    ]
