# Generated by Django 4.1.3 on 2023-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
