# Generated by Django 4.1.3 on 2023-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0008_alter_link_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='abnormal_traffic',
            fields=[
                ('intrusion_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('paths', models.CharField(max_length=255)),
                ('victim_ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'abnormal_traffic',
            },
        ),
    ]
