# Generated by Django 4.1.3 on 2023-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0009_abnormal_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_time', models.DateTimeField()),
                ('link_id', models.CharField(max_length=255)),
                ('throughput', models.IntegerField()),
                ('delay', models.DecimalField(decimal_places=12, max_digits=16)),
                ('jitter', models.DecimalField(decimal_places=12, max_digits=16)),
                ('loss', models.DecimalField(decimal_places=12, max_digits=16)),
            ],
            options={
                'db_table': 'link_stat',
            },
        ),
    ]
