# Generated by Django 4.1.3 on 2023-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuxi', '0010_link_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormal_traffic',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abnormal_traffic',
            name='intrusion_time',
            field=models.DateTimeField(),
        ),
    ]
